CLASS zbp_pra_mf_r_musicfestival DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zpra_mf_r_musicfestival .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_PRA_MF_R_MUSICFESTIVAL IMPLEMENTATION.

ENDCLASS.
