CLASS zbp_pra_mf_r_musicfestival DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zpra_mf_r_musicfestival .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    CLASS-DATA:
      bgmc_processes TYPE STANDARD TABLE OF REF TO if_bgmc_process.
ENDCLASS.



CLASS ZBP_PRA_MF_R_MUSICFESTIVAL IMPLEMENTATION.
ENDCLASS.
