CLASS zcl_pra_mf_enum_criticality DEFINITION PUBLIC ABSTRACT FINAL.

  PUBLIC SECTION.
    CONSTANTS neutral  TYPE int4 VALUE 0.
    CONSTANTS negative TYPE int4 VALUE 1.
    CONSTANTS critical TYPE int4 VALUE 2.
    CONSTANTS positive TYPE int4 VALUE 3.
ENDCLASS.



CLASS ZCL_PRA_MF_ENUM_CRITICALITY IMPLEMENTATION.
ENDCLASS.
