CLASS zcl_pra_mf_enum_visit_status DEFINITION PUBLIC ABSTRACT FINAL.

  PUBLIC SECTION.
    CONSTANTS pending   TYPE ZPRA_MF_C_VisitTP-Status VALUE 'P'.
    CONSTANTS cancelled TYPE ZPRA_MF_C_VisitTP-Status VALUE 'C'.
    CONSTANTS booked    TYPE ZPRA_MF_C_VisitTP-Status VALUE 'B'.
ENDCLASS.



CLASS ZCL_PRA_MF_ENUM_VISIT_STATUS IMPLEMENTATION.
ENDCLASS.
