CLASS ztc_pra_mf_vstr_o4_odata DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZTC_PRA_MF_VSTR_O4_ODATA IMPLEMENTATION.
ENDCLASS.
